export type Language = 'es' | 'en' | 'fr' | 'pt';

export const translations: Record<Language, any> = {
  es: {
    sidebar: { dashboard: 'Dashboard Principal', escandallos: 'Escandallos Dinámicos', inventario: 'Inventario Predictivo', trazabilidad: 'Trazabilidad y Calidad', ecosistema: 'Ecosistema Comercial GHL', integracion: 'Integración Middleware', cumplimiento: 'Cumplimiento Legal', workflow: 'Workflow Tarta Personalizada', online: 'Sistema Online' },
    common: { updateData: 'Actualizar Datos', search: 'Buscar receta...', ingredient: 'Ingrediente', qty: 'Cantidad', unitPrice: 'Precio Unit.', subtotal: 'Subtotal', var3m: 'Var 3M', status: 'Estado', provider: 'Proveedor', track: 'Rastrear', type: 'Tipo', campaign: 'Campaña', dates: 'Fechas', conversion: 'Conversión', segment: 'Segmento', score: 'Score', profile: 'Perfil', action: 'Acción', event: 'Evento', method: 'Método', client: 'Cliente', step: 'Paso', data: 'Datos', logic: 'Lógica', loyalty: 'Fidelización', ok: 'OK', warning: 'BAJO', critical: 'CRÍTICO' },
    dashboard: { title: 'Dashboard Ejecutivo', subtitle: 'Visión global del negocio en tiempo real', margin: 'Margen Bruto Promedio', waste: 'Merma Mensual', autoOrders: 'Pedidos Automatizados', eInvoice: 'Facturación Electrónica', ltv: 'LTV Cliente Medio', marginEvol: 'Evolución Margen Bruto (6 meses)', salesSeason: 'Ventas por Temporada', wasteDist: 'Distribución de Mermas', topProducts: 'Top 5 Productos Rentabilidad', activeAlerts: 'Alertas Activas', criticalStock: 'Stock Crítico', expiringSoon: 'Caducidad Próxima', activeCampaign: 'Campaña Activa' },
    escandallos: { title: 'Escandallos Dinámicos', subtitle: 'Fichas Maestras de Receta (BOM) y Simulador de Costes', suggestedRRP: 'PVP Sugerido', margin: 'Margen', costMP: 'Coste MP', mod: 'MOD', energy: 'Energía+Overhead', totalCost: 'COSTE TOTAL', simTitle: 'Simulador de Escenarios', selectIng: 'Seleccionar Ingrediente', priceVar: 'Variación de Precio', impact: 'Impacto en Catálogo', engineText: 'El motor de cálculo propaga en tiempo real el nuevo coste a todas las recetas que contienen' },
    inventario: { title: 'Inventario Predictivo (IA)', subtitle: 'Gestión FEFO, predicción de demanda y alertas IoT', genOrder: 'Generar Pedido Automático', ingStatus: 'Estado de Ingredientes', currentStock: 'Stock Actual', reorderPt: 'Punto Reorden', demand7d: 'Demanda 7D', lotControl: 'Control de Lotes (Lógica FEFO)', lot: 'Lote', expiry: 'Caducidad', shelfLife: 'Vida Útil', predEngine: 'Motor Predictivo', upcomingEvents: 'Eventos Próximos (Multiplicadores)', alerts: 'Alertas de Caducidad / IoT', autoBlock: 'Bloqueo Automático', exp48h: 'Caducidad < 48h', iotOk: 'Sensores IoT OK' },
    trazabilidad: { title: 'Trazabilidad y Calidad', subtitle: 'Control de lotes End-to-End y alertas de calidad', cert: 'Certificado IFS Food', flow: 'Flujo de Control de Lotes', rec: 'Recepción MP', store: 'Almacenamiento FEFO', prod: 'Producción', exp: 'Expedición', invTrace: 'Trazabilidad Inversa', qualityAlerts: 'Alertas de Calidad', affectedLot: 'Lote Afectado', autoAction: 'Acción Automatizada' },
    ecosistema: { title: 'Ecosistema Comercial GHL', subtitle: 'Funnels, IA Conversacional y Fidelización RFM', newCamp: 'Lanzar Nueva Campaña', funnels: 'Funnels de Temporada', starProd: 'Producto Estrella', funnelStruct: 'Estructura de Funnel Estándar', rfm: 'Sistema de Fidelización RFM', autoActionGhl: 'Acción Automatizada (GHL)', sdr: 'SDR Inteligente (IA)' },
    integracion: { title: 'Integración Middleware', subtitle: 'Arquitectura de datos entre ERP, GHL, Make y Pasarelas', apiConn: 'APIs Conectadas', e2eFlow: 'Flujo de Cierre de Venta End-to-End', apiMap: 'Mapa de Comunicación API', origDest: 'Origen → Destino', keyPayload: 'Payload Clave', sysArch: 'Arquitectura de Sistemas' },
    cumplimiento: { title: 'Cumplimiento Legal', subtitle: 'Normativa Española: Facturación Electrónica y Fiscalidad', auditOk: 'Auditoría OK (2026)', implStatus: 'Estado de Implementación Normativa', norm: 'Normativa', keyReq: 'Requisito Clave', progress: 'Progreso', genInvoice: 'Generación Factura Electrónica', linkedOrder: 'Pedido Vinculado', outFormat: 'Formato de Salida', signEmit: 'Firmar y Emitir (XAdES)', xmlPreview: 'Vista Previa XML', dlXml: 'Descargar XML' },
    workflow: { title: 'Workflow Tarta Personalizada', subtitle: 'Flujo visual paso a paso de reserva y producción', autoProcess: 'Proceso Automatizado' }
  },
  en: {
    sidebar: { dashboard: 'Main Dashboard', escandallos: 'Dynamic Costing', inventario: 'Predictive Inventory', trazabilidad: 'Traceability & Quality', ecosistema: 'GHL Commercial Ecosystem', integracion: 'Middleware Integration', cumplimiento: 'Legal Compliance', workflow: 'Custom Cake Workflow', online: 'System Online' },
    common: { updateData: 'Update Data', search: 'Search recipe...', ingredient: 'Ingredient', qty: 'Quantity', unitPrice: 'Unit Price', subtotal: 'Subtotal', var3m: '3M Var', status: 'Status', provider: 'Provider', track: 'Track', type: 'Type', campaign: 'Campaign', dates: 'Dates', conversion: 'Conversion', segment: 'Segment', score: 'Score', profile: 'Profile', action: 'Action', event: 'Event', method: 'Method', client: 'Client', step: 'Step', data: 'Data', logic: 'Logic', loyalty: 'Loyalty', ok: 'OK', warning: 'LOW', critical: 'CRITICAL' },
    dashboard: { title: 'Executive Dashboard', subtitle: 'Global business overview in real-time', margin: 'Avg Gross Margin', waste: 'Monthly Waste', autoOrders: 'Automated Orders', eInvoice: 'E-Invoicing', ltv: 'Avg Customer LTV', marginEvol: 'Gross Margin Evolution (6 months)', salesSeason: 'Sales by Season', wasteDist: 'Waste Distribution', topProducts: 'Top 5 Profitable Products', activeAlerts: 'Active Alerts', criticalStock: 'Critical Stock', expiringSoon: 'Expiring Soon', activeCampaign: 'Active Campaign' },
    escandallos: { title: 'Dynamic Costing', subtitle: 'Master Recipe Files (BOM) & Cost Simulator', suggestedRRP: 'Suggested RRP', margin: 'Margin', costMP: 'Raw Mat Cost', mod: 'Direct Labor', energy: 'Energy+Overhead', totalCost: 'TOTAL COST', simTitle: 'Scenario Simulator', selectIng: 'Select Ingredient', priceVar: 'Price Variation', impact: 'Catalog Impact', engineText: 'The calculation engine propagates the new cost in real-time to all recipes containing' },
    inventario: { title: 'Predictive Inventory (AI)', subtitle: 'FEFO Management, demand prediction & IoT alerts', genOrder: 'Generate Auto Order', ingStatus: 'Ingredients Status', currentStock: 'Current Stock', reorderPt: 'Reorder Point', demand7d: '7D Demand', lotControl: 'Lot Control (FEFO Logic)', lot: 'Lot', expiry: 'Expiry', shelfLife: 'Shelf Life', predEngine: 'Predictive Engine', upcomingEvents: 'Upcoming Events (Multipliers)', alerts: 'Expiry / IoT Alerts', autoBlock: 'Auto Block', exp48h: 'Expiry < 48h', iotOk: 'IoT Sensors OK' },
    trazabilidad: { title: 'Traceability & Quality', subtitle: 'End-to-End lot control and quality alerts', cert: 'IFS Food Certificate', flow: 'Lot Control Flow', rec: 'Raw Mat Reception', store: 'FEFO Storage', prod: 'Production', exp: 'Dispatch', invTrace: 'Reverse Traceability', qualityAlerts: 'Quality Alerts', affectedLot: 'Affected Lot', autoAction: 'Automated Action' },
    ecosistema: { title: 'GHL Commercial Ecosystem', subtitle: 'Funnels, Conversational AI & RFM Loyalty', newCamp: 'Launch New Campaign', funnels: 'Seasonal Funnels', starProd: 'Star Product', funnelStruct: 'Standard Funnel Structure', rfm: 'RFM Loyalty System', autoActionGhl: 'Automated Action (GHL)', sdr: 'Smart SDR (AI)' },
    integracion: { title: 'Middleware Integration', subtitle: 'Data architecture between ERP, GHL, Make & Gateways', apiConn: 'Connected APIs', e2eFlow: 'End-to-End Sales Closing Flow', apiMap: 'API Communication Map', origDest: 'Source → Destination', keyPayload: 'Key Payload', sysArch: 'Systems Architecture' },
    cumplimiento: { title: 'Legal Compliance', subtitle: 'Spanish Regulations: E-Invoicing & Taxation', auditOk: 'Audit OK (2026)', implStatus: 'Regulation Implementation Status', norm: 'Regulation', keyReq: 'Key Requirement', progress: 'Progress', genInvoice: 'E-Invoice Generation', linkedOrder: 'Linked Order', outFormat: 'Output Format', signEmit: 'Sign & Emit (XAdES)', xmlPreview: 'XML Preview', dlXml: 'Download XML' },
    workflow: { title: 'Custom Cake Workflow', subtitle: 'Visual step-by-step booking and production flow', autoProcess: 'Automated Process' }
  },
  fr: {
    sidebar: { dashboard: 'Tableau de Bord', escandallos: 'Coûts Dynamiques', inventario: 'Inventaire Prédictif', trazabilidad: 'Traçabilité et Qualité', ecosistema: 'Écosystème GHL', integracion: 'Intégration Middleware', cumplimiento: 'Conformité Légale', workflow: 'Workflow Gâteau Personnalisé', online: 'Système en Ligne' },
    common: { updateData: 'Mettre à jour', search: 'Chercher recette...', ingredient: 'Ingrédient', qty: 'Quantité', unitPrice: 'Prix Unit.', subtotal: 'Sous-total', var3m: 'Var 3M', status: 'Statut', provider: 'Fournisseur', track: 'Tracer', type: 'Type', campaign: 'Campagne', dates: 'Dates', conversion: 'Conversion', segment: 'Segment', score: 'Score', profile: 'Profil', action: 'Action', event: 'Événement', method: 'Méthode', client: 'Client', step: 'Étape', data: 'Données', logic: 'Logique', loyalty: 'Fidélisation', ok: 'OK', warning: 'BAS', critical: 'CRITIQUE' },
    dashboard: { title: 'Tableau de Bord Exécutif', subtitle: 'Aperçu global de l\'entreprise en temps réel', margin: 'Marge Brute Moyenne', waste: 'Pertes Mensuelles', autoOrders: 'Commandes Automatisées', eInvoice: 'Facturation Électronique', ltv: 'LTV Client Moyen', marginEvol: 'Évolution Marge Brute (6 mois)', salesSeason: 'Ventes par Saison', wasteDist: 'Distribution des Pertes', topProducts: 'Top 5 Produits Rentables', activeAlerts: 'Alertes Actives', criticalStock: 'Stock Critique', expiringSoon: 'Expiration Proche', activeCampaign: 'Campagne Active' },
    escandallos: { title: 'Coûts Dynamiques', subtitle: 'Fiches Recettes (BOM) & Simulateur de Coûts', suggestedRRP: 'Prix Conseillé', margin: 'Marge', costMP: 'Coût MP', mod: 'Main d\'œuvre', energy: 'Énergie+Frais', totalCost: 'COÛT TOTAL', simTitle: 'Simulateur de Scénarios', selectIng: 'Sélectionner Ingrédient', priceVar: 'Variation de Prix', impact: 'Impact Catalogue', engineText: 'Le moteur de calcul propage en temps réel le nouveau coût à toutes les recettes contenant' },
    inventario: { title: 'Inventaire Prédictif (IA)', subtitle: 'Gestion FEFO, prédiction de demande & alertes IoT', genOrder: 'Générer Commande Auto', ingStatus: 'Statut des Ingrédients', currentStock: 'Stock Actuel', reorderPt: 'Point de Commande', demand7d: 'Demande 7J', lotControl: 'Contrôle des Lots (FEFO)', lot: 'Lot', expiry: 'Expiration', shelfLife: 'Durée de Vie', predEngine: 'Moteur Prédictif', upcomingEvents: 'Événements à Venir (Multiplicateurs)', alerts: 'Alertes Expiration / IoT', autoBlock: 'Blocage Auto', exp48h: 'Expiration < 48h', iotOk: 'Capteurs IoT OK' },
    trazabilidad: { title: 'Traçabilité et Qualité', subtitle: 'Contrôle des lots de bout en bout et alertes qualité', cert: 'Certificat IFS Food', flow: 'Flux de Contrôle des Lots', rec: 'Réception MP', store: 'Stockage FEFO', prod: 'Production', exp: 'Expédition', invTrace: 'Traçabilité Inverse', qualityAlerts: 'Alertes Qualité', affectedLot: 'Lot Affecté', autoAction: 'Action Automatisée' },
    ecosistema: { title: 'Écosystème Commercial GHL', subtitle: 'Funnels, IA Conversationnelle & Fidélisation RFM', newCamp: 'Lancer Nouvelle Campagne', funnels: 'Funnels Saisonniers', starProd: 'Produit Phare', funnelStruct: 'Structure Funnel Standard', rfm: 'Système de Fidélisation RFM', autoActionGhl: 'Action Automatisée (GHL)', sdr: 'SDR Intelligent (IA)' },
    integracion: { title: 'Intégration Middleware', subtitle: 'Architecture de données entre ERP, GHL, Make & Passerelles', apiConn: 'APIs Connectées', e2eFlow: 'Flux de Clôture de Vente de Bout en Bout', apiMap: 'Carte de Communication API', origDest: 'Origine → Destination', keyPayload: 'Payload Clé', sysArch: 'Architecture Systèmes' },
    cumplimiento: { title: 'Conformité Légale', subtitle: 'Réglementation Espagnole : Facturation Électronique & Fiscalité', auditOk: 'Audit OK (2026)', implStatus: 'Statut Implémentation Normative', norm: 'Normative', keyReq: 'Exigence Clé', progress: 'Progrès', genInvoice: 'Génération Facture Électronique', linkedOrder: 'Commande Liée', outFormat: 'Format de Sortie', signEmit: 'Signer et Émettre (XAdES)', xmlPreview: 'Aperçu XML', dlXml: 'Télécharger XML' },
    workflow: { title: 'Workflow Gâteau Personnalisé', subtitle: 'Flux visuel étape par étape de réservation et production', autoProcess: 'Processus Automatisé' }
  },
  pt: {
    sidebar: { dashboard: 'Dashboard Principal', escandallos: 'Custos Dinâmicos', inventario: 'Inventário Preditivo', trazabilidad: 'Rastreabilidade e Qualidade', ecosistema: 'Ecossistema GHL', integracion: 'Integração Middleware', cumplimiento: 'Conformidade Legal', workflow: 'Workflow Bolo Personalizado', online: 'Sistema Online' },
    common: { updateData: 'Atualizar Dados', search: 'Buscar receita...', ingredient: 'Ingrediente', qty: 'Quantidade', unitPrice: 'Preço Unit.', subtotal: 'Subtotal', var3m: 'Var 3M', status: 'Status', provider: 'Fornecedor', track: 'Rastrear', type: 'Tipo', campaign: 'Campanha', dates: 'Datas', conversion: 'Conversão', segment: 'Segmento', score: 'Score', profile: 'Perfil', action: 'Ação', event: 'Evento', method: 'Método', client: 'Cliente', step: 'Passo', data: 'Dados', logic: 'Lógica', loyalty: 'Fidelização', ok: 'OK', warning: 'BAIXO', critical: 'CRÍTICO' },
    dashboard: { title: 'Dashboard Executivo', subtitle: 'Visão global do negócio em tempo real', margin: 'Margem Bruta Média', waste: 'Perda Mensal', autoOrders: 'Pedidos Automatizados', eInvoice: 'Faturamento Eletrônico', ltv: 'LTV Cliente Médio', marginEvol: 'Evolução Margem Bruta (6 meses)', salesSeason: 'Vendas por Temporada', wasteDist: 'Distribuição de Perdas', topProducts: 'Top 5 Produtos Rentáveis', activeAlerts: 'Alertas Ativos', criticalStock: 'Estoque Crítico', expiringSoon: 'Vencimento Próximo', activeCampaign: 'Campanha Ativa' },
    escandallos: { title: 'Custos Dinâmicos', subtitle: 'Fichas Mestras de Receita (BOM) e Simulador de Custos', suggestedRRP: 'Preço Sugerido', margin: 'Margem', costMP: 'Custo MP', mod: 'Mão de Obra', energy: 'Energia+Despesas', totalCost: 'CUSTO TOTAL', simTitle: 'Simulador de Cenários', selectIng: 'Selecionar Ingrediente', priceVar: 'Variação de Preço', impact: 'Impacto no Catálogo', engineText: 'O motor de cálculo propaga em tempo real o novo custo para todas as receitas que contêm' },
    inventario: { title: 'Inventário Preditivo (IA)', subtitle: 'Gestão FEFO, previsão de demanda e alertas IoT', genOrder: 'Gerar Pedido Automático', ingStatus: 'Status dos Ingredientes', currentStock: 'Estoque Atual', reorderPt: 'Ponto de Pedido', demand7d: 'Demanda 7D', lotControl: 'Controle de Lotes (Lógica FEFO)', lot: 'Lote', expiry: 'Validade', shelfLife: 'Vida Útil', predEngine: 'Motor Preditivo', upcomingEvents: 'Próximos Eventos (Multiplicadores)', alerts: 'Alertas de Validade / IoT', autoBlock: 'Bloqueio Automático', exp48h: 'Validade < 48h', iotOk: 'Sensores IoT OK' },
    trazabilidad: { title: 'Rastreabilidade e Qualidade', subtitle: 'Controle de lotes de ponta a ponta e alertas de qualidade', cert: 'Certificado IFS Food', flow: 'Fluxo de Controle de Lotes', rec: 'Recepção MP', store: 'Armazenamento FEFO', prod: 'Produção', exp: 'Expedição', invTrace: 'Rastreabilidade Inversa', qualityAlerts: 'Alertas de Qualidade', affectedLot: 'Lote Afetado', autoAction: 'Ação Automatizada' },
    ecosistema: { title: 'Ecossistema Comercial GHL', subtitle: 'Funnels, IA Conversacional e Fidelização RFM', newCamp: 'Lançar Nova Campanha', funnels: 'Funnels Sazonais', starProd: 'Produto Estrela', funnelStruct: 'Estrutura Padrão de Funnel', rfm: 'Sistema de Fidelização RFM', autoActionGhl: 'Ação Automatizada (GHL)', sdr: 'SDR Inteligente (IA)' },
    integracion: { title: 'Integração Middleware', subtitle: 'Arquitetura de dados entre ERP, GHL, Make e Gateways', apiConn: 'APIs Conectadas', e2eFlow: 'Fluxo de Fechamento de Venda Ponta a Ponta', apiMap: 'Mapa de Comunicação API', origDest: 'Origem → Destino', keyPayload: 'Payload Chave', sysArch: 'Arquitetura de Sistemas' },
    cumplimiento: { title: 'Conformidade Legal', subtitle: 'Regulamentação Espanhola: Faturamento Eletrônico e Fiscalidade', auditOk: 'Auditoria OK (2026)', implStatus: 'Status de Implementação Normativa', norm: 'Normativa', keyReq: 'Requisito Chave', progress: 'Progresso', genInvoice: 'Geração de Fatura Eletrônica', linkedOrder: 'Pedido Vinculado', outFormat: 'Formato de Saída', signEmit: 'Assinar e Emitir (XAdES)', xmlPreview: 'Visualização XML', dlXml: 'Baixar XML' },
    workflow: { title: 'Workflow Bolo Personalizado', subtitle: 'Fluxo visual passo a passo de reserva e produção', autoProcess: 'Processo Automatizado' }
  }
};

export type TranslationKey = string;
